steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA",
        "backend/fastapi_app",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA",
        "backend/flask_app",
      ]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/worker:$SHORT_SHA", "worker"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/worker:$SHORT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "fastapi-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "flask-app"
      - "--image"
      - "gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA"
      - "--platform"
      - "managed"
      - "--region"
      - "${_REGION}"
      - "--allow-unauthenticated"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "container"
      - "clusters"
      - "get-credentials"
      - "${_GKE_CLUSTER}"
      - "--region"
      - "${_REGION}"
      - "--project"
      - "$PROJECT_ID"

  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/worker-deployment"
      - "worker=gcr.io/$PROJECT_ID/worker:$SHORT_SHA"
      - "--namespace"
      - "default"

timeout: "1200s"

images:
  - "gcr.io/$PROJECT_ID/fastapi-app:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/worker:$SHORT_SHA"

substitutions:
  _REGION: "us-central1"
  _GKE_CLUSTER: "petscream-cluster"
