name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up GCP credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker

      - name: Build & push images
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app:${{ github.sha }} backend/fastapi_app
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }} backend/flask_app
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/worker:${{ github.sha }} worker

          docker push gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/worker:${{ github.sha }}

      - name: Deploy FastAPI to Cloud Run
        run: |
          gcloud run deploy fastapi-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/fastapi-app:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet

      - name: Deploy Flask to Cloud Run
        run: |
          gcloud run deploy flask-app \
            --image gcr.io/${{ secrets.GCP_PROJECT }}/flask-app:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --quiet

      - name: Deploy Worker to GKE
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} \
            --region ${{ secrets.GCP_REGION }} \
            --project ${{ secrets.GCP_PROJECT }}
          kubectl set image deployment/worker-deployment \
            worker=gcr.io/${{ secrets.GCP_PROJECT }}/worker:${{ github.sha }}
