name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "DESTROY" to confirm destruction'
        required: true

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'DESTROY' }}
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init -input=false

      - name: Destroy Terraform-managed resources
        working-directory: terraform
        run: terraform destroy -auto-approve

      - name: Finished
        run: echo "All Terraform-managed infrastructure has been destroyed."
