name: Terraform Force-Unlock State

on:
  workflow_dispatch:
    inputs:
      lock_id:
        description: "Terraform lock ID to force-unlock"
        required: true

jobs:
  unlock:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.9"

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Force-Unlock Terraform State
        working-directory: terraform
        run: |
          terraform force-unlock -force ${{ github.event.inputs.lock_id }}

      - name: Confirm Lock File Removal
        run: |
          LOCK_FILE="gs://petscream-tfstate/terraform/state/default.tflock"
          echo "Checking for $LOCK_FILE"
          if gsutil -q stat "$LOCK_FILE"; then
            echo "::error ::Lock file still exists at $LOCK_FILE"
            exit 1
          else
            echo "Lock file is gone: state is unlocked."
          fi
